Removed QueryByEmbedder && QueryByInvoker
Codemodder applied same changes to trino without any differences

The following tests failed:

POMOperatorDependencyQueryTest::testBasicQuery
java.lang.AssertionError: Dependencies are not empty

POMOperatorDependencyQueryTest::testTemporaryDirectory
java.lang.AssertionError: Temp Directory ends up existing

POMOperatorDependencyQueryTest::testAllQueryTypes
java.lang.AssertionError: Dependencies are not empty

POMOperatorDependencyQueryTest::testFailedUnsafeQuery
Unexpected exception type thrown ==> expected: <java.lang.IllegalStateException> but was: <java.lang.AssertionError>
java.lang.AssertionError: Dependencies are empty

POMOperatorMultipomTest::testWithMultiplePomsBasicWithVersionProperty
java.lang.AssertionError: Dependency org.dom4j:dom4j:jar:2.0.3 must be present in context io.codemodder.plugins.maven.operator.ProjectModel@31e3b882 (null)

POMOperatorMultipomTest::testWithMultiplePomsBasicNoVersionProperty
java.lang.AssertionError: Dependency org.dom4j:dom4j:jar:2.0.3 must be present in context io.codemodder.plugins.maven.operator.ProjectModel@72a45b71 (null)