Removed CheckLocalRepositoryDirCommand, QueryType.UNSAFE
Removed CheckLocalRepositoryDirCommand class and code related to it that is no longer used

Removed QueryType.UNSAFE since there are no commands that use that type

Add queryType != QueryType.NONE conditions since we are setting that type to some POM Documents but there are no commands that use that query type

Removed POMOperatorDependencyQueryTest::testFailedUnsafeQuery since we are not using Unsafe query type

POMOperatorDependencyQueryTest::testAllQueryTypes removed the query type UNSAFE

Codemodder applies same changes to Trino without differences

Test failures:

POMOperatorDependencyQueryTest::testTemporaryDirectory
java.lang.AssertionError: Temp Directory ends up existing

POMOperatorMultipomTest::testWithMultiplePomsBasicWithVersionProperty

POMOperatorMultipomTest::testWithMultiplePomsBasicNoVersionProperty

Dependency org.dom4j:dom4j:jar:2.0.3 must be present in context io.codemodder.plugins.maven.operator.ProjectModel@11963225 ([org.dom4j:dom4j:jar:UNKNOWN])

NOTE ABOUT THOSE TWO PREVIOUS TESTS... IT finds the dependency but version is set as UNKNOWN that's why it says it is not being found