OFFLINE = TRUE
Setting offline to true to stop making request to remote maven repository doesn't affect to codemodder - trino results

HOWEVER
Tests were broken, specifically POMOperatorDependencyQueryTest::testAllQueryTypes

assertion failed since dependencies were empty and it is not expected

[Test worker] WARN io.codemodder.plugins.maven.operator.EmbedderFacade - Oops:
org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model for org.codehaus.mojo:versions-maven-plugin:2.9-SNAPSHOT
[FATAL] Non-resolvable parent POM for org.codehaus.mojo:versions-maven-plugin:2.9-SNAPSHOT: Could not find artifact org.codehaus.mojo:mojo-parent:pom:63 and 'parent.relativePath' points at wrong local POM @