AbstractQueryCommand::findMaven
I commented all logic for the findMaven searching process and leave the IllegalStateException to be always thrown

Codemodder changes were applied to trino repo and no differences were found. Same changes were applied compared to current codemodder main version.

For tests, 4 new tests failed besides the previous two failing ones:

NEW - POMOperatorDependencyQueryTest::testBasicQuery
NEW - POMOperatorDependencyQueryTest::testOnCompositeSyntheticDependencyIncompleteWithoutParsing
NEW - POMOperatorMultipomTest::testWithMultiplePomsBasicWithVersionProperty
NEW - POMOperatorMultipomTest::testWithMultiplePomsBasicNoVersionProperty

they're not expecting the following exception:
java.lang.IllegalStateException: Missing Maven Home / Executable